### ISSUE TITLE
Evaluation results by batch?

### ISSUE THREAD

**Issue by Natxo-ia** [ThilinaRajapakse/pytorch-transformers-classification#10]
Hi,

I am just launching again the roberta model, and I just realized that the evaluation results are printed several times and showing different numbers, maybe by evaluation batch size? Is the last the average?

**Comment by ThilinaRajapakse** [comment]
If `eval_all_checkpoints` is set to `True` in the `args` dict, then the evaluation will be run for all the checkpoints. A checkpoint will be made at every step given by `save_steps`, i.e for `"save_steps": 2000`, the model will be saved at every 2000 steps. You can check the `outputs` directory to see the checkpoints. The final output of the evaluation results is the evaluation results of the final model.

**Comment by Natxo-ia** [comment]
Meaning that the last printed output (tagged as `***** Eval results outputs *****`) is the final output right?

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/50815888/65015018-5e078500-d946-11e9-9d99-bc6f3843f3eb.png">

In the previous screenshot would be 0.9294993661807587?

**Comment by ThilinaRajapakse** [comment]
Yes, exactly.

**Comment by Natxo-ia** [comment]
Great, thanks
