### ISSUE TITLE
Possible typo in README.md

### ISSUE THREAD

**Issue by dallidalli** [ThilinaRajapakse/pytorch-transformers-classification#11]
Hi,
in your README.md it states that the model name for the MNLI-fine-tuned RoBERTa model is (also) 'roberta-large'. I did not test it yet, but I assume that the correct model name (according to https://huggingface.co/pytorch-transformers/pretrained_models.html) is 'roberta-large-mnli'.
Cheers

**Comment by ThilinaRajapakse** [comment]
You are right, good catch! Details aren't my strong suit. :dizzy_face:

Fixed it.

**Comment by dallidalli** [comment]
Glad to help, great repo and article!
