### ISSUE TITLE
task_name

### ISSUE THREAD

**Issue by Natxo-ia** [ThilinaRajapakse/pytorch-transformers-classification#12]
In the `args` dictionary we have this entry:  `'task_name': 'binary',`. 

Later it is used in here:

```
task = args['task_name']
processor = processors[task]()
```

I have tried to change this name (i.e. yelp) but it gives me an error (not too much info in the error, it only shows the name of the task I wrote). With `binary` works well. Is it the name for the task (i.e. a description) or maybe the type of text classification task?

**Comment by ThilinaRajapakse** [comment]
It's basically the name of the task you are doing that is used to get the following information.

```
processors = {
    "binary": BinaryProcessor
}

output_modes = {
    "binary": "classification"
}
```
These are defined in `utils.py`. It's only useful when you want to reuse the code for multiple tasks, for example by writing your own `DataProcessor`. But yes, it's too cryptic. The error message should be clearer at the very least.

**Comment by Natxo-ia** [comment]
Ok, it's clear. Thanks.
