### ISSUE TITLE
WARMUP_PROPORTION equivalent

### ISSUE THREAD

**Issue by NiAmL** [ThilinaRajapakse/pytorch-transformers-classification#14]
Hi,

In the `BERT_binary_text_classification` repo we used a parameter called `WARMUP_PROPORTION` (set to 0.1). Which is the equivalent in this repo?

Thanks.

**Comment by ThilinaRajapakse** [comment]
You can use either `warmup_steps` or `warmup_ratio`. If `warmup_steps` is given, it will be used, else `warmup_ratio` is used.

Note, I just pushed the `warmup_ratio` commit, so you'll need to update to use it. `warmup_steps` was there from the beginning, but you have to explicitly set a number of steps.

**Comment by NiAmL** [comment]
I saw that this parameter was added, so I can close this issue.
