### ISSUE TITLE
Available languages

### ISSUE THREAD

**Issue by NiAmL** [ThilinaRajapakse/pytorch-transformers-classification#16]
Hi,

Is there a place where we can check the pre-trained languages available for the transformer models (XLNet, RoBERTa, and XLM) up-to-date?

Thanks

**Comment by ThilinaRajapakse** [comment]
Yes, they are available in the Hugging Face docs. I can post a link later if you need.

**Comment by Natxo-ia** [comment]
Can be [these ones](https://huggingface.co/transformers/pretrained_models.html?highlight=languages)?

**Comment by Natxo-ia** [comment]
I was trying to find the languages for roBERTa, as I supposed all the BERT ones would be but I am not sure about this assumption...

**Comment by ThilinaRajapakse** [comment]
I don't think Roberta has multilingual support as of yet. At least, I haven't been able to find anything of the sort.

**Comment by NiAmL** [comment]
Ok, let's see if any of these models cover more languages in the near future...
