### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'items'

### ISSUE THREAD

**Issue by NiAmL** [ThilinaRajapakse/pytorch-transformers-classification#22]
I got this error after activating the option to evaluate during training:

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/50815888/66368125-0eecc700-e9bd-11e9-8f6c-301be2d9f27f.png">

I have tracked the `results` variable but I couldn't find the origin. Supposedly it is a dictionary type, as it has been initialized with `results = {}`.

**Comment by ThilinaRajapakse** [comment]
I pushed a fix, can you try it now? The issue was I modified the evaluation function to return both the results and the wrong predictions. The evaluate_during_training option was only expecting the results.

**Comment by NiAmL** [comment]
Yeah, now looks its working. Thanks

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/50815888/66369467-88d37f00-e9c2-11e9-98f4-953794c7553e.png">
