### ISSUE TITLE
ImportError: cannot import name 'convert_examples_to_features' from 'utils'

### ISSUE THREAD

**Issue by nalcvp** [ThilinaRajapakse/pytorch-transformers-classification#25]
After running the first cell in the run_model.ipynb. Anyone understand this issue?

**Comment by ThilinaRajapakse** [comment]
That is simply importing a function from the utils.py file. Is the file (and the function in the file) present? Perhaps your file paths or python version is messed up.

**Comment by nalcvp** [comment]
Ok thanks, fixed! Didn't even notice that file. Utils is a package in python so that's the source of my confusion
