### ISSUE TITLE
How to use other models without loading them from internet?

### ISSUE THREAD

**Issue by Azamat25** [ThilinaRajapakse/pytorch-transformers-classification#28]
I have terrible internet connection. So i would like to ask you what modifications I should make to use other models if I already downloaded them from internet? for example xlm-mlm-tlm-xnli15-1024 model? Should I create 'cache' file in the same folder and put there .bin file? and what part of code i should modify to use that model? Thanks

**Comment by ThilinaRajapakse** [comment]
```
model = model_class.from_pretrained(<path_to_dir_containing_model_files>)
```

This should do the trick.

**Comment by Azamat25** [comment]
config = config_class.from_pretrained("model_files/xlm-mlm-tlm-xnli15-1024-config.json", num_labels=2, finetuning_task=args['task_name'])
tokenizer = tokenizer_class.from_pretrained("model_files/xlm-mlm-tlm-xnli15-1024-vocab.json")
model = model_class.from_pretrained("model_files/xlm-mlm-tlm-xnli15-1024-pytorch_model.bin")

is that correct? I am receving UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte. Thanks!

**Comment by ThilinaRajapakse** [comment]
The paths should be the path to the directory, not the file itself.

```
config = config_class.from_pretrained("model_files/", num_labels=2, finetuning_task=args['task_name'])
tokenizer = tokenizer_class.from_pretrained("model_files/")
model = model_class.from_pretrained("model_files/")
```
