### ISSUE TITLE
Running Inference

### ISSUE THREAD

**Issue by ricknichols84** [ThilinaRajapakse/pytorch-transformers-classification#37]
Hello Thilina, thank you for this repo.

Question: After I've fine-tuned a roberta model for sentence classification, how do I run inference on a sample sentence in real-time? Is there a specific function in your code base you can point me to?

**Comment by ThilinaRajapakse** [comment]
This repo doesn't really have built-in support for that, although it shouldn't be hard to implement. I recommend you use [Simple Transformers](https://github.com/ThilinaRajapakse/simpletransformers), which does support this (and a lot more) out of the box.

**Comment by ricknichols84** [comment]
thank you
