### ISSUE TITLE
ValueError: Number of processes must be at least 1

### ISSUE THREAD

**Issue by Natxo-ia** [ThilinaRajapakse/pytorch-transformers-classification#4]
Hi,

When training the model, I get this error:

<img width="955" alt="Untitled" src="https://user-images.githubusercontent.com/50815888/64767998-ba495e00-d56e-11e9-8cc1-566788f49ecc.png">

I am just running the code for the first time, I haven't checked it too much yet...

**Comment by Natxo-ia** [comment]
Mmm and what could it be? I just run it again and got the same error. This are the resources that I have allocated:

![image](https://user-images.githubusercontent.com/50815888/64935741-d6077980-d878-11e9-9112-f358677db988.png)

**Comment by ThilinaRajapakse** [comment]
Try setting process_count to 1 in the call to `convert_examples_to_features()` inside the `load_and_cache_examples()` function.

```
features = convert_examples_to_features(examples, label_list, args['max_seq_length'], tokenizer, output_mode,
            cls_token_at_end=bool(args['model_type'] in ['xlnet']),            # xlnet has a cls token at the end
            cls_token=tokenizer.cls_token,
            sep_token=tokenizer.sep_token,
            cls_token_segment_id=2 if args['model_type'] in ['xlnet'] else 0,
            pad_on_left=bool(args['model_type'] in ['xlnet']),                 # pad on the left for xlnet
            pad_token_segment_id=4 if args['model_type'] in ['xlnet'] else 0,
            process_count=1)
```

**Comment by Natxo-ia** [comment]
I got this error when I changed it:

<img width="959" alt="Untitled" src="https://user-images.githubusercontent.com/50815888/64936075-26330b80-d87a-11e9-9b58-ee520a081f00.png">

Anyway, let me review the code, because I have been disconnected last days from this, so I want to check that I have been following all the steps correctly.

**Comment by ThilinaRajapakse** [comment]
Are you using a local copy (local to your Google Drive, that is)? I think this bug was there in the original notebook, but it was fixed later.

**Comment by Natxo-ia** [comment]
Yeah maybe is that. I know is better to fork to your repo so we have the updates/fixes instantly, but I like first to understand the code recreating it in my own notebook. I am using Colab linked to Google Drive. I will check that and I will let you know. Thanks.

**Comment by ThilinaRajapakse** [comment]
Understandable! Let me know how it goes.

**Comment by Natxo-ia** [comment]
With fresh head is more easy to see things. There was two things that I changed and make it worked: 

- When making dataframes BERT friendly I didn't pass the parameter ` columns=train_df_bert.columns` to the `to.csv` function.
- In the function `load_and_cache_examples` I was not including the colab add-in parameter `undersample_scale_factor=0.1`.

Maybe the first point was the one causing the error? Anyway sorry for my lapsus, I will keep iterating it and let you know if I see any suspicious bug.

**Comment by ThilinaRajapakse** [comment]
Weird. Neither of those things should be throwing a "number of processes" error as far as I can tell. That error comes from the multiprocessing used for converting examples to features. Oh well, we don't need to worry about it if it's working!

**Comment by Natxo-ia** [comment]
I was facing again this problem with another iteration and I changed this:

`process_count = cpu_count() - 2`

for this

`process_count = 1`

in the function `convert_examples_to_features` of the `utils.py` file, and it worked. I am working on Colab. It makes sense to you?

**Comment by ThilinaRajapakse** [comment]
Yes, that would fix all multiprocessing related issues at the expense of not using multiprocessing at all. I think you can get away with setting it to 2 on Colab. Setting it to 2 should speed things up a bit but setting it to 1 will ensure that you won't get multiprocessing related errors.
