### ISSUE TITLE
Num epoch and other standard configurations

### ISSUE THREAD

**Issue by sekarpdkt** [ThilinaRajapakse/pytorch-transformers-classification#40]
Hi 
I am **unable** to find config options for number of epochs to run etc.. Am I missing something very basic here?

Thanks
Sekar

**Comment by ThilinaRajapakse** [comment]
They are in the 2nd cell of run_model.ipynb.

_Please consider using the [Simple Transformers](https://github.com/ThilinaRajapakse/simpletransformers) library as this repo is no longer kept up to date._

**Comment by sekarpdkt** [comment]
Opps.. I actually using that link only. The question is for that library? In that also unable to find config for epochs

**Comment by ThilinaRajapakse** [comment]
You can find them [here](https://github.com/ThilinaRajapakse/simpletransformers#default-settings).

There's also example scripts that demonstrate how you can use the various models.

**Comment by sekarpdkt** [comment]
Thanks.  I got it. I need to handle it here

model = ClassificationModel('bert', 'bert-base-uncased',args={'reprocess_input_data': True, ** 'num_train_epochs': 5, ** 'overwrite_output_dir': True})

**Comment by ThilinaRajapakse** [comment]
Yup.
