### ISSUE TITLE
 FileNotFoundError: [Errno 2] File b'data/dev.csv' does not exist: b'data/dev.csv'

### ISSUE THREAD

**Issue by Azamat25** [ThilinaRajapakse/pytorch-transformers-classification#5]
in the colab file this cell has a mistake:

train_df = pd.read_csv(prefix + 'dev.csv', header=None)
train_df.head()
FileNotFoundError  

i assume its supposed to be:
train_df = pd.read_csv(prefix + 'test.csv', header=None)

**Comment by ThilinaRajapakse** [comment]
Fixed.
